### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by jsnlmr** [learn-co-curriculum/javascript-hide-and-seek#20]
I am unable to run the tests for this lab. The results from tests return 1 failing with a "before all hooks" error.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jsntime.

We have updated the materials and believe your issue to have been resolved. In order to access the new materials, you will need to delete your existing fork of this lab and revisit the lesson on learn.co to refork.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
